---
- name: Install build-essential
  apt: pkg=build-essential
 
- name: Install autoconf
  apt: pkg=autoconf
 
- name: Install libncurses5-dev
  apt: pkg=libncurses5-dev
 
- name: Install libwxgtk2.8-dev
  apt: pkg=libwxgtk2.8-dev
 
- name: Install libgl1-mesa-dev
  apt: pkg=libgl1-mesa-dev
 
- name: Install libglu1-mesa-dev
  apt: pkg=libglu1-mesa-dev
 
- name: Install libpng3
  apt: pkg=libpng3
 
- name: Install libssh-dev
  apt: pkg=libssh-dev
 
- name: Install unixodbc-dev
  apt: pkg=unixodbc-dev
 
- name: Get Erlang
  get_url: url=http://www.erlang.org/download/otp_src_17.0.tar.gz dest=/tmp/otp_src_17.0.tar.gz
 
- name: Unarchive Erlang
  command: chdir=/tmp tar xvf /tmp/otp_src_17.0.tar.gz
 
- name: Install Erlang
  command: chdir=/tmp/otp_src_17.0 ./configure
 
- name: Build Erlang
  command: chdir=/tmp/otp_src_17.0 make
 
- name: Install Erlang
  command: chdir=/tmp/otp_src_17.0 make install
 
- name: Get Elixir
  git: repo=https://github.com/elixir-lang/elixir.git dest=/opt/elixir version=stable
 
- name: Build Elixir
  command: chdir=/opt/elixir make install
 
- name: Get Dynamo
  git: repo=https://github.com/dynamo/dynamo.git dest=/opt/dynamo
 
- name: Get Dynamo dependencies
  command: chdir=/opt/dynamo mix deps.get
  
- name: Build Dynamo
  command: chdir=/opt/dynamo mix do local.rebar, compile
